name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-8.1.457.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3768/212/RoughlyEnoughItems-8.1.457.jar"
hash-format = "sha1"
hash = "ff5ebb1de3f87e5321d748c102dd6a542032796"

[update]
[update.curseforge]
file-id = 3768212
project-id = 310111
