name = "True Darkness"
filename = "darkness-fabric-mc118-2.0.89.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Ja7zPEaN/versions/fabric-mc118-2.0.89/darkness-fabric-mc118-2.0.89.jar"
hash-format = "sha1"
hash = "146d81ca7f10c2306af25e9363eac36c4579a7f0"

[update]
[update.modrinth]
mod-id = "Ja7zPEaN"
version = "2FFtZocO"
