name = "YUNG's Better Strongholds (Fabric)"
filename = "YungsBetterStrongholds-1.18.2-Fabric-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/925/YungsBetterStrongholds-1.18.2-Fabric-2.1.0.jar"
hash-format = "sha1"
hash = "002787e73e47c193a1dc316c63ea914a7c8bcb0c"

[update]
[update.curseforge]
file-id = 3777925
project-id = 480684
